[package]
edition = "2021"
name = "near-private-data-client"
version = "0.1.0"

[dependencies]
anyhow = "1.0.69"
async-std = "1.12.0"
base64ct = {version = "1.5.3", features = ["alloc"]}
chacha20poly1305 = "0.10.1"
chrono = "0.4.23"
console = "0.15.5"
crossterm = "0.26.1"
dialoguer = "0.10.3"
dotenvy = "0.15.6"
envy = "0.4.2"
near-crypto = "0.15.0"
near-jsonrpc-client = "0.4.1"
near-jsonrpc-primitives = "0.15.0"
near-primitives = "0.15.0"
rand = "0.7.0"
serde = "1.0.152"
serde_json = "1.0.93"
sha2 = "0.10.6"
tokio = {version = "~1.19", features = ["full"]}
tui = "0.19.0"
x25519-dalek = "1"
