[package]
edition = { workspace = true }
name = "near-private-data-client"
version = { workspace = true }
readme = { workspace = true }
homepage = { workspace = true }
authors = { workspace = true }

[dependencies]
pretty_env_logger = "0.5.0"
log = "0.4.19"
anyhow = "1.0.69"
base64ct = { version = "1.5.3", features = ["alloc"] }
bincode = "1.3.3"
chacha20poly1305 = "0.10.1"
chrono = "0.4.23"
console = "0.15.5"
dialoguer = "0.10.3"
dotenvy = "0.15.6"
ed25519-dalek = "1.0.1"
envy = "0.4.2"
rand = "0.7.0"
serde = "1.0.152"
serde_json = "1.0.93"
near-private-data-verification-gadget = { path = "../verify" }

crossterm = "0.26.1"
tui = "0.19.0"

near-crypto = "0.17.0"
near-jsonrpc-client = "0.6.0"
near-jsonrpc-primitives = "0.17.0"
near-primitives = "0.17.0"

sha2 = "0.10.6"
x25519-dalek = "1"

# FIXME: remove
async-std = "1.12.0"
futures = "0.3.28"
tokio = { version = "1", features = ["full"] }
