[package]
edition = "2021"
name = "client"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15.6"
ed25519-dalek = "1.0.1"
envy = "0.4.2"
near-crypto = "0.15.0"
near-jsonrpc-client = "0.4.1"
near-jsonrpc-primitives = "0.15.0"
near-primitives = "0.15.0"
rand = "0.7.0"
serde = "1.0.152"
serde_json = "1.0.93"
sha2 = "0.10.6"
tokio = {version = "~1.19", features = ["full"]}
x25519-dalek = "1.2.0"
