[package]
edition = { workspace = true }
name = "near-private-data-client"
version = { workspace = true }
readme = { workspace = true }
homepage = { workspace = true }
authors = { workspace = true }

[dependencies]
pretty_env_logger = "0.5"
log = "0.4"
anyhow = "1"
base64ct = { version = "1.5", features = ["alloc"] }
bincode = "1.3"
chacha20poly1305 = "0.10"
chrono = "0.4"
console = "0.15"
dialoguer = "0.10"
dotenvy = "0.15"
ed25519-dalek = "1"
envy = "0.4"
rand = "0.7"
serde = "1"
serde_json = "1"
typenum = "1"
near-private-data-verification-gadget = { path = "../verify" }

crossterm = "0.26"
tui = "0.19"

near-crypto = "0.17"
near-jsonrpc-client = "0.6"
near-jsonrpc-primitives = "0.17"
near-primitives = "0.17"

sha2 = "0.10"
x25519-dalek = "1"

# FIXME: remove
async-std = "1.12"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
ark-crypto-primitives = "0.4.0"
