[package]
edition = "2021"
name = "near-private-data-client"
version = "0.1.0"

[dependencies]
anyhow = "1.0.69"
base64ct = {version = "1.5.3", features = ["alloc"]}
chacha20poly1305 = "0.10.1"
dotenvy = "0.15.6"
ed25519-dalek = "1"
envy = "0.4.2"
near-crypto = "0.15.0"
near-jsonrpc-client = "0.4.1"
near-jsonrpc-primitives = "0.15.0"
near-primitives = "0.15.0"
rand = "0.7.0"
serde = "1.0.152"
serde_json = "1.0.93"
sha2 = "0.10.6"
tokio = {version = "~1.19", features = ["full"]}
x25519-dalek = "1"
