[package]
authors = ["Jacob Lindahl <lindahl@prg.is.titech.ac.jp>"]
edition = "2021"
name = "fc-public-key-registry-contract"
version = "0.1.0"

[dependencies]
near-sdk.workspace = true
near-sdk-contract-tools.workspace = true

[lib]
crate-type = ["cdylib"]
