[package]
authors = ["Jacob Lindahl <jacob.lindahl@near.org>"]
edition = "2021"
name = "near-private-data-public-key-registry-contract"
version = "0.1.0"

[dependencies]
near-sdk = "5.5.0"
near-sdk-contract-tools = "3.0.2"

[lib]
crate-type = ["cdylib"]
